// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System;

public static class DataTableRegistry
{
    public static readonly DataTableEntry[] Entries =
    {
        new DataTableEntry("ItemTable", typeof(ItemTable)),
    };
}

public readonly struct DataTableEntry
{
    public readonly string FileName;
    public readonly Type TableType;

    public DataTableEntry(string fileName, Type tableType)
    {
        FileName = fileName;
        TableType = tableType;
    }
}
