// <auto-generated>
// 由 DataTableGenerator 生成，请勿手动修改
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

public sealed class ItemTableRow
{
    /// <summary>唯一标识，主键</summary>
    public int Id { get; set; }
    /// <summary>物品名称</summary>
    public string Name { get; set; }
    /// <summary>图标资源ID</summary>
    public int IconId { get; set; }
    /// <summary>标签数组</summary>
    public int[] Tags { get; set; }
}

public sealed class ItemTable : IDataTable
{
    readonly Dictionary<int, ItemTableRow> _rows = new();

    public void Load(string json)
    {
        var file = JsonConvert.DeserializeObject<DataTableFile<ItemTableRow>>(json);
        _rows.Clear();
        foreach (var row in file.rows)
        {
            _rows[row.Id] = row;
        }
    }

    public ItemTableRow GetById(int id)
    {
        if (_rows.TryGetValue(id, out var row))
            return row;
        throw new KeyNotFoundException($"ItemTable 未找到 Id={id}");
    }

    public bool TryGetById(int id, out ItemTableRow row) => _rows.TryGetValue(id, out row);

    public IReadOnlyDictionary<int, ItemTableRow> All => _rows;
}
