[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
ANTHROPIC_AUTH_TOKEN = "sk-08da3abae34f40ed8aeba978ccbf9c1a"
ANTHROPIC_BASE_URL = "https://api.deepseek.com/anthropic"
ANTHROPIC_DEFAULT_HAIKU_MODEL = "deepseek-v4-flash"
ANTHROPIC_DEFAULT_OPUS_MODEL = "deepseek-v4-pro"
ANTHROPIC_DEFAULT_OPUS_MODEL_NAME = "deepseek-v4-pro"
ANTHROPIC_DEFAULT_SONNET_MODEL = "deepseek-v4-pro"
ANTHROPIC_DEFAULT_SONNET_MODEL_NAME = "deepseek-v4-pro"
ANTHROPIC_MODEL = "deepseek-v4-pro"
